config/routes.rb
Rails.application.routes.draw do
  # Error handling
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Root
  root 'home#index'

  # Links
  get 'links', to: 'links#index'
  get 'link/:id', to: 'links#show', as: 'link'
  post '/links', to: 'links#create'

  # Short link (Slug)
  get "/s/:slug", to: 'links#shorten'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :visit_histories

  before_validation :remove_url_protocol
  after_validation :add_url_protocol

  validates :slug, presence: true, uniqueness: true
  validates :target_url, presence: true, url:true

  def generate_short_link
    if Rails.env.production?
      "https://#{Rails.application.secrets.host}/s/#{slug}"
    else
      "http://#{Rails.application.secrets.host}/s/#{slug}"
    end
  end

  private

  def add_url_protocol
    unless target_url[/\Ahttp:\/\//] || target_url[/\Ahttps:\/\//]
      self.target_url = "https://#{target_url}"
    end
  end

  def remove_url_protocol
    if target_url[/\Ahttp:\/\//] || target_url[/\Ahttps:\/\//]
      uri = URI(target_url)
      self.target_url = uri.hostname + uri.path
    end
  end
end

app/models/visit_history.rb
class VisitHistory < ApplicationRecord
  belongs_to :link

  validates :geolocation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404, layout:'error'
  end

  def internal_server_error
    render status: 500, layout:'error'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  add_flash_types :success, :error, :slug

  def index
    @link = Link.new
  end
end

app/controllers/links_controller.rb
require 'nokogiri'
require 'open-uri'

class LinksController < ApplicationController
  def index
    @links = Link.order('clicks DESC').all
    @visit_histories_count = VisitHistory.all.count
  end

  def show
    @link = Link.find(params[:id])

    # Get the title of target URL
    begin
      @title = Nokogiri::HTML.parse(URI.open(@link.target_url)).title
    rescue
      @title = "N/A"
    end
  end

  def create
    shortener = Shortener.new(link_params[:target_url])
    @link = shortener.create_link

    if @link.new_record?
      redirect_to root_path, :flash => {
        :error => 'Invalid link, please try again!'
      }
    else
      redirect_to link_path(@link.id), :flash => {
        :success => 'Successfully created your short link!',
      }
    end
  end

  def shorten
    @link = Link.find_by(slug: params[:slug])

    # Track every clicks
    @link.clicks += 1
    @link.save

    # Get geolocation in production
    if Rails.env.production?
      location = "#{request.location.city}, #{request.location.country}"
    else
      location = "Kuala Lumpur"
    end

    VisitHistory.create(
      link: @link,
      geolocation: location
    )

    redirect_to @link.target_url, allow_other_host: true
  end

  private
  def link_params
    params.require(:link).permit(:target_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="bg-green-100 py-16 sm:py-24">
  <div class="relative sm:py-16">
    <div aria-hidden="true" class="hidden sm:block">
      <div class="absolute inset-y-0 left-0 w-1/2 bg-green-200 rounded-r-3xl"></div>
      <svg class="absolute top-8 left-1/2 -ml-3" width="404" height="392" fill="none" viewBox="0 0 404 392">
        <defs>
          <pattern id="8228f071-bcee-4ec8-905a-2a059a2cc4fb" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
            <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor" />
          </pattern>
        </defs>
        <rect width="404" height="392" fill="url(#8228f071-bcee-4ec8-905a-2a059a2cc4fb)" />
      </svg>
    </div>
    <div class="mx-auto max-w-md px-4 sm:max-w-3xl sm:px-6 lg:max-w-7xl lg:px-8">
      <div class="relative rounded-2xl px-6 py-10 bg-green-600 overflow-hidden shadow-xl sm:px-12 sm:py-20">
        <div aria-hidden="true" class="absolute inset-0 -mt-72 sm:-mt-32 md:mt-0">
          <svg class="absolute inset-0 h-full w-full" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 1463 360">
            <path class="text-green-500 text-opacity-40" fill="currentColor" d="M-82.673 72l1761.849 472.086-134.327 501.315-1761.85-472.086z" />
            <path class="text-green-700 text-opacity-40" fill="currentColor" d="M-217.088 544.086L1544.761 72l134.327 501.316-1761.849 472.086z" />
          </svg>
        </div>
        <div class="relative">
          <div class="sm:text-center">
            <h2 class="text-3xl font-extrabold text-white tracking-tight sm:text-4xl">Shorten your URL with one click</h2>
            <p class="mt-6 mx-auto max-w-2xl text-lg text-green-200">No one enjoy typing <a target="_blank" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="text-xs underline">https://www.youtube.com/watch?v=dQw4w9WgXcQ</a> to the search bar</p>
          </div>
          <%= form_with model: @link, class: "mt-12 sm:mx-auto sm:max-w-lg sm:flex" do |form| %>
            <div class="min-w-0 flex-1">
              <%= form.label :target_url, "URL", class: "sr-only" %>
              <%= form.text_field :target_url , required: true, placeholder: "Enter your link here", class: "block w-full border border-transparent rounded-md px-5 py-3 text-base text-gray-900 placeholder-gray-500 shadow-sm focus:outline-none focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-green-600" %>
            </div>
            <div class="mt-4 sm:mt-0 sm:ml-3">
              <%= form.submit "Shorten", class: "block w-full rounded-md border border-transparent px-5 py-3 bg-green-500 text-base font-medium text-white shadow hover:bg-green-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-green-600 sm:px-10 cursor-pointer" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="h-full bg-green-100">
  <head>
    <title>URL Shortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">
    <%= render 'layouts/partials/header' %>
    <%= render 'layouts/partials/flash' %>
    <%= yield %>
    <%= render 'layouts/partials/watermark' %>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html lang="en" class="h-full">
  <head>
    <title>Error Page</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == "error" %>
    <div>
      <div class="rounded-md bg-red-50 p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800"><%= msg %></h3>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/partials/_header.html.erb
<div class="bg-white ">
  <div class="block">
    <div class="border-b border-gray-200">
      <nav class="-mb-px flex justify-center" aria-label="Tabs">
        <% if current_page?(root_path) %>
          <%= link_to "Home", root_path, class: "border-green-500 text-green-600 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
          <%= link_to "Dashboard", links_path, class: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
        <% elsif current_page?(links_path) %>
          <%= link_to "Home", root_path, class: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
          <%= link_to "Dashboard", links_path, class: "border-green-500 text-green-600 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
        <% else %>
          <%= link_to "Home", root_path, class: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
          <%= link_to "Dashboard", links_path, class: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm" %>
        <% end %>
      </nav>
    </div>
  </div>
</div>

app/views/links/index.html.erb
<div class="py-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
  <div class="bg-green-600 pt-12 sm:pt-16 rounded-3xl">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="max-w-4xl mx-auto text-center">
        <h2 class="text-3xl font-extrabold text-white sm:text-4xl">Link Dashboard</h2>
        <p class="mt-3 text-xl text-white sm:mt-4">View the statistics of all created links with the table below</p>
      </div>
    </div>

    <div class="rounded-3xl mt-10 pb-12 bg-green-600 sm:pb-16">
      <div class="relative">
        <div class="absolute inset-0 h-1/2 bg-green-600"></div>
        <div class="bg-green-600 relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="max-w-4xl mx-auto">
            <dl class="rounded-lg bg-white shadow-lg sm:grid sm:grid-cols-2">
              <div class="flex flex-col border-b border-gray-100 p-6 text-center sm:border-0 sm:border-r">
                <dt class="order-2 mt-2 text-lg leading-6 font-medium text-gray-500">Number of Links</dt>
                <dd class="order-1 text-5xl font-extrabold text-green-600"><%= @links.count %></dd>
              </div>
              <div class="flex flex-col border-t border-b border-gray-100 p-6 text-center sm:border-0 sm:border-l sm:border-r">
                <dt class="order-2 mt-2 text-lg leading-6 font-medium text-gray-500">Number of Visits</dt>
                <dd class="order-1 text-5xl font-extrabold text-green-600"><%= @visit_histories_count %></dd>
              </div>
            </dl>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-10 flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Shortened Link</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Target Link</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Clicks</th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">View</span>
              </th>
            </tr>
            </thead>
            <tbody>

            <% @links.each do |v| %>
              <tr class="bg-white">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-400 underline"><a target="_blank" href="<%= v.generate_short_link %>"><%= v.generate_short_link %></a></td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-400 underline"><a target="_blank" href="<%= v.target_url %>"><%= v.target_url %></a></td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= v.clicks %></td>
                  <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <%= link_to "View", link_path(v), class: "text-indigo-600 hover:text-indigo-900"%>
                  </td>
            <% end.empty? and begin %>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">No record yet</td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"></td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"></td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/links/show.html.erb
<div class="bg-green-100">
  <div class="max-w-7xl mx-auto px-4 py-12 sm:px-6 lg:py-16 lg:px-8">
    <div class="py-10 px-6 bg-green-600 rounded-3xl sm:py-16 sm:px-12 lg:p-20 lg:flex lg:items-center">
      <div class="lg:w-0 lg:flex-1">
        <h2 class="text-3xl font-extrabold tracking-tight text-white">Your shortened link is</h2>
        <p class="mt-4 max-w-3xl text-lg text-green-100">
          Your link has been clicked <%= @link.clicks %> time(s). Track the originating geolocation and timestamp of each visit to your shortened link with the table below.
        </p>
        <p class="mt-4 max-w-3xl text-lg text-green-100">
          Your original link is <a target="_blank" href="<%= @link.target_url %>" class="text-base underline"><%= @link.target_url %></a> with the
          title tag of "<%= @title %>".
        </p>
      </div>
      <div class="mt-12 sm:w-full sm:max-w-md lg:mt-0 lg:ml-8 lg:flex-1">
        <div class="sm:flex">
          <label for="shortened-url" class="sr-only">Shortened Link</label>
          <input type="text" id="shortened-url" value="<%= @link.generate_short_link %>" name="shortened-url" class="w-full border-white px-5 py-3 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-green-700 focus:ring-white rounded-md">
        </div>
      </div>
    </div>

    <div class="flex flex-col mt-10">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Geolocation</th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Timestamp</th>
              </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <% @link.visit_histories.each do |v| %>
                  <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= v.geolocation %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= v.created_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></td>
                  </tr>
                <% end.empty? and begin %>
                  <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Your link has yet to visited</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>